name: Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v2

    - name: Push main release
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Pushing to the latest tag"
        gh release create latest --title "Latest release from main" --notes "This release gets updated on each commit to main" || true
        gh release upload latest "README.md#ReadmeAndStuff.md" --clobber

        version="v0.2.0"
        echo "Making sure the release ${version} is online"
        gh release create "${version}" --title "${version}" --notes-file "docs/ReleaseNotes/${version}.md" || true
        gh release upload "${version}" "README.md#ReadmeAndStuff.md" || true

